# Intro to NumPy

In [1]:
import numpy as np

## data types

In [2]:
# normal int contradicts with pythons builtin int,
# Thats why np.int_ is used, which is equal to int32
# int8 means 8 bit or 2 bytes, int16 - 16 bits, int32

# dtype obtains the data type of the array

a = np.int_([1,2,3])
print(a, "Type is", a.dtype)

c = np.int8([5,8,9])
print(c, "Type is", c.dtype)

[1 2 3] Type is int32
[5 8 9] Type is int8


In [3]:
# float in numpy contradicts with pythons builtin float.
# Thats why np.float_ is used here which is equal to float64
# float32, float64 or double()

demo_1 = 10/3
b = np.float_([2,4,demo_1])
print(b, "Type is", b.dtype)

demo_2 = 10/3
d = np.float32([2,4,demo_2])
print(d, "Type is", d.dtype)


[2.         4.         3.33333333] Type is float64
[2.        4.        3.3333333] Type is float32


In [4]:
# Data type can be initialized also like below (Recommended)

e = np.array([1,2,3], dtype='f')
print(e, "Type is", e.dtype)


[1. 2. 3.] Type is float32


In [5]:
# converting one type to another

f = e.astype(int)
print(f, "Type is", f.dtype)

# or 

g = np.int16(e)
print(g, "Type is", g.dtype)

[1 2 3] Type is int32
[1 2 3] Type is int16


[Float vs Double](https://hackr.io/blog/float-vs-double)

# array creation